services:
  hadev:
    container_name: hadev
    build:
      context: ../../core
      dockerfile: Dockerfile.dev
    ports:
      - 8123:8123/tcp
    volumes:
      - ../..:/workspaces:cached
      - ../../devcontainers/hadev/config:/config
      - ../custom_components:/config/custom_components
